---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Get server name
      set_fact:
        server_name: "{{ ansible_hostname }}"

    - name: Check disk usage
      shell: df -hP / | awk 'NR==2{print $5}' | cut -d '%' -f1
      register: disk_usage
      changed_when: false

    - name: Send Discord notification if disk usage is high
      when: disk_usage.stdout|int >= 80 and (disk_usage.rc == 0 or disk_usage.rc == 204)
      uri:
        url: https://your-hook
        method: POST
        body_format: json
        body: '{"content": "Server {{ server_name }} - disk usage is at {{ disk_usage.stdout }}%"}'
      delegate_to: localhost
      ignore_errors: yes
