---
- name: Update Pi-Hole and Notify Discord
  hosts: all
  become: true
  tasks:
    - name: Update Pi-Hole
      shell: >
        curl -sSL https://install.pi-hole.net | bash /dev/stdin --reconfigure
      args:
        executable: /bin/bash

    - name: Notify Discord
      uri:
        url: "https://discord.com/api/webhooks/1154893277510770698/aqMPGP58pC6qBZ4tHe7yK8OQPBVXqDTo7o8RiiJmMC1h30zvMD2CP4X1sbsvuNyhMcv_"
        method: POST
        body_format: json
        body:
          content: "Pi-Hole has been updated!"
        status_code: 204
        validate_certs: no
